openapi: 3.0.1
info:
  title: storedata
  description: API Definition of storedata
  version: 1.0.0
servers:
- url: http://localhost:8290/store
paths:
  /order/{orderId}:
    get:
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
